stripetest/payment/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
    PaymentListView,
#     CustomerDetailView,
    PaymentCreateView,
    PaymentChargeView,
)

urlpatterns = [
    url(
        r'^$',
        PaymentListView.as_view(),
        name='payment_list'
    ),
    url(
        r'^create/$',
        PaymentCreateView.as_view(),
        name='payment_create'
    ),
    url(
        r'^(?P<pk>[0-9]+)/charge/$',
        PaymentChargeView.as_view(),
        name='payment_charge'
    ),
]

stripetest/urls.py
import debug_toolbar

from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^payment/', include('stripetest.payment.urls', namespace="payment")),
]

urlpatterns = [
    # path('__debug__/', include(debug_toolbar.urls)),

    # For django versions before 2.0:
    url(r'^__debug__/', include(debug_toolbar.urls)),

] + urlpatterns

stripetest/payment/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import stripe

from django.db import models

from django.conf import settings
from django_mysql.models import JSONField


# Create your models here.

class Payment(models.Model):
    CHARGE_STATUS_OPTIONS = (
        ("succeeded", "Succeeded"),
        ("failed", "Failed"),
        ("pending", "Pending"),
    )
    name = models.CharField(blank=True, null=True, max_length=250)
    billing_token = models.CharField(blank=True, null=True, max_length=250)
    billing_data = JSONField(blank=True, null=True, default=dict)
    customer_data = JSONField(blank=True, null=True, default=dict)
    customer_id = models.CharField(blank=True, null=True, max_length=250)
    charge_data = JSONField(blank=True, null=True, default=dict)
    status = models.CharField(max_length=25, choices=CHARGE_STATUS_OPTIONS, blank=True, null=True)

    def get_stripe_key(secret=False, publishable=False):
        if secret:
            return settings.STRIPE_KEYS[secret]
        elif publishable:
            return settings.STRIPE_KEYS[publishable]

stripetest/payment/forms.py
from django import forms

from .models import Payment

class PaymentForm(forms.ModelForm):
    
    class Meta:
        model = Payment
        fields = ('name',)

stripetest/payment/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json
import stripe

from django.conf import settings
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, CreateView, TemplateView
from django.urls import reverse

from .models import Payment
from .forms import PaymentForm

# Create your views here.

class PaymentListView(ListView):
    model = Payment
    template_name = 'payment/payment_list.html'

    def get_queryset(self):
        return Payment.objects.all()

class PaymentCreateView(CreateView):
    model = Payment
    form_class = PaymentForm
    template_name = 'payment/payment_create.html'

    def get_success_url(self):
        return reverse('payment:payment_list')

    def get_context_data(self, **kwargs):
        context = super(PaymentCreateView, self).get_context_data(**kwargs)
        context['stripe_publishable_key'] = settings.STRIPE_DEMO_PUBLISHABLE_KEY
        return context

    def post(self, request, *args, **kwargs):
        stripe_billing_data = request.POST

        email = stripe_billing_data.get('email')
        paymentmethod_id = stripe_billing_data.get('stripeToken')

        stripe.api_key = settings.STRIPE_DEMO_SECRET_KEY

        # Create a Customer
        try:
            customer = stripe.Customer.create(
                email=email,
                metadata={
                    'backgroundcheck': "BC-1234556",
                    'datacheck': "CH-123456",
                    'check_type': "Check Name",
                    'customer': "Bilal Inc",
                },
            )
            customer_id = customer.get('id')
        except stripe.CardError as e:
            messages.error(self.request, e.message)
            return HttpResponseRedirect(self.get_failure_url())
        except stripe.error.StripeError as e:
            messages.error(self.request, e.message)
            return HttpResponseRedirect(self.get_failure_url())

        payment_method = stripe.PaymentMethod.attach(
            paymentmethod_id,
            customer=customer_id
        )
        customer_data = stripe.Customer.modify(
            customer_id,
            invoice_settings={
                'default_payment_method': paymentmethod_id
            }
        )
        customer_data = stripe.Customer.retrieve(customer_id)

        Payment.objects.get_or_create(
            billing_token=paymentmethod_id,
            billing_data=json.dumps(stripe_billing_data),
            customer_data=json.loads(str(customer_data)),
            customer_id=customer_id,
        )
        return HttpResponseRedirect(self.get_success_url())

class PaymentChargeView(TemplateView):
    template_name = 'payment/payment_charge.html'

    def get_success_url(self):
        return reverse('payment:payment_list')

    def get_object(self):
        return get_object_or_404(
            Payment,
            pk=self.kwargs.get('pk'),
        )

    def get_context_data(self, **kwargs):
        context = super(PaymentChargeView, self).get_context_data(**kwargs)
        context['payment'] = self.get_object()
        return context

    def post(self, request, *args, **kwargs):
        payment = self.get_object()
        stripe.api_key = settings.STRIPE_DEMO_SECRET_KEY

        price_to_charge = 2500

        try:
            charge = stripe.PaymentIntent.create(
                amount=int(round(price_to_charge)),
                currency='gbp',
                payment_method_types=['card'],
                customer=payment.customer_id,
                payment_method=payment.billing_token,
                off_session='one_off',
                confirm=True,
                metadata={
                    'backgroundcheck': "BC-1234556",
                    'datacheck': "CH-123456",
                    'check_type': "Check Name",
                    'customer': "Bilal Inc",
                },
            )
            payment.charge_data = json.loads(str(charge))
            payment.save()
            stripe_customer = stripe.Customer.retrieve(payment.customer_id)
            # stripe_customer.delete()
        # except Exception as e:
            # messages.error(self.request, e.message)
            # return 'error'
        # except stripe.CardError as e:
        #     messages.error(self.request, e.message)
        #     return 'error'
        # except stripe.error.StripeError as e:
        #     messages.error(self.request, e.message)
        #     return 'error'
        # if charge.get('status') == 'succeeded':
        #     return HttpResponseRedirect(self.get_success_url())

stripetest/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock title %}</title>
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script type="text/javascript"  src="https://code.jquery.com/jquery-3.4.1.slim.min.js"integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8="crossorigin="anonymous"></script>
    {% block style %}{% endblock style%}
    {% block head %}{% endblock head %}
    {% block script %}{% endblock script %}
</head>
<body id="{% block body_id %}{% endblock %}">
    <header id="header">
    </header>

    <div class="container">
        <div id="pageheader">
            {% block pageheader %}
            {% endblock pageheader %}
        </div>
        <div class="content">
            {% block content %}
            {% endblock content %}
        </div>
    </div>

    <footer id="footer">
        Copyright &copy; {% now "Y" %}
    </footer>
</body>
</html>

stripetest/templates/payment/payment_charge.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Make Payment{% endblock title %}
{% block pageheader %}
    <h3>Make Payment</h3>
{% endblock pageheader %}

{% block script %}
{% endblock script %}

{% block content %}

    <form action="{% url 'payment:payment_charge' payment.id %}" method="post" id="payment-form">
    	{% csrf_token %}
		<button id="charge_button" class="btn btn-primary"> Charge</button>
    </form>

{% endblock content %}

stripetest/templates/payment/payment_create.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Make Payment{% endblock title %}
{% block pageheader %}
    <h3>Make Payment</h3>
{% endblock pageheader %}

{% block script %}
    <script src="https://js.stripe.com/v3/"></script>
    <script type="text/javascript" charset="utf-8">
        var stripe = Stripe('{{ stripe_publishable_key }}');
        var elements = stripe.elements();
    </script>
{% endblock script %}

{% block content %}

    <form action="{% url 'payment:payment_create' %}" method="post" id="payment-form">
        {% csrf_token %}
            <div>

                <div>
                    <div>
                        <h4">Billing Information</h4>
                    </div>
                    <div>
                        <div>
                            <label for="cardholder_name">Name</label>
                            <div id="cardholder-name">
                                <input id="cardholder_name" type="text" placeholder="Name" class="textinput textInput form-control">
                            </div>
                        </div>
                     
                        <div>
                            <label for="cardholder_email">Email Address</label>
                            <div id="cardholder-email">
                                <input id="cardholder_email" type="text" name="email" placeholder="Email Address" class="textinput textInput form-control">
                            </div>
                        </div>
                        
                        <div>
                            <label for="cardholder_street">Street</label>
                            <div id="cardholder-street">
                                <input id="cardholder_street" type="text" placeholder="Street" class="textinput textInput form-control">
                            </div>
                        </div>

                        <div>
                            <label for="cardholder_city">City</label>
                            <div id="cardholder-city">
                                <input id="cardholder_city" type="text" placeholder="City" class="textinput textInput form-control">
                            </div>
                        </div>

                        <div>
                            <label for="cardholder_post_code">Post Code</label>
                            <div id="cardholder-post_code">
                                <input id="cardholder_post_code" type="text" placeholder="Post Code" class="textinput textInput form-control">
                            </div>
                        </div>
                    </div>
                </div>

                <div>
                    <div>
                        <h4>Card Information</h4>
                    </div>
                    <div>
                        <div>
                            <label for="card-number">Number</label>
                            <div id="card-number">
                                <!-- A Stripe Element for card number will be inserted here. -->
                            </div>
                        </div>

                        <div>
                            <label for="card-expiry">Expiry</label>
                            <div id="card-expiry">
                                <!-- A Stripe Element for card expiry will be inserted here. -->
                            </div>
                        </div>

                        <div>
                            <label for="card-cvc">CVC</label>
                            <div id="card-cvc">
                                <!-- A Stripe Element card cvc will be inserted here. -->
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Used to display Element errors. -->
                <div id="card-errors" role="alert" class="hidden-xs-up alert alert-danger" style="margin: 10px 0;">
                    <i class="fa fa-exclamation-circle" aria-hidden="true"></i>
                    <span class="message"></span>
                </div>
            </div>

            <!-- 5786 4369 4349 4425 -->
            <div class="float-xs-right">
                <button id="charge_button" class="btn btn-primary"> Pay</button>
            </div>
    </form>

    <script type="text/javascript" src="{% static 'js/public/stripe_payment.js' %}"></script>
    {% comment %}
    {% endcomment %}

{% endblock content %}

stripetest/templates/payment/payment_list.html
{% extends 'base.html' %}

{% block title %}Payment List{% endblock title %}
{% block pageheader %}
    <h3>Payment List</h3>
{% endblock pageheader %}

{% block content %}
    TEST
    <table>
    	<tbody>
		    {% for payment in payment_list %}
    		<tr>>
    			<td>{{ payment }}</td>
    			<td><a href="{% url 'payment:payment_charge' payment.id %}" class="btn btn-primary">Charge</a></td>
    		</tr>
		    {% endfor %}
		</tbody>
	</table>

    <a href="{% url 'payment:payment_create' %}" class="btn btn-primary">Pay</a>

{% endblock content %}